name: Publish Python distribution to PyPI and TestPyPI
on:
  workflow_dispatch:
  push:
    tags:
      - '*'
jobs:
  build-n-publish:
    name: Publish Python distribution to PyPI and TestPyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install flit
        run: >-
          python -m
          pip install
          flit
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          flit build
  #    - name: Publish distribution to TestPyPI
  #      uses: pypa/gh-action-pypi-publish@master
  #      with:
  #        user: __token__
  #        password: ${{ secrets.testpypi_token }}
  #        repository_url: https://test.pypi.org/legacy/
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.pypi_token }}